server:
  port: 2022
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.2:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/demo/*.xml
  global-config:
    db-config:
      id-type: auto
